version: '3.8'

services:
  # Service Base de données
  mongo:
    image: mongo:6.0
    container_name: event_db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes:
      - mongo_data:/data/db

  # Interface visuelle (Optionnel mais recommandé pour le dev)
  mongo-express:
    image: mongo-express
    container_name: event_db_ui
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpassword
      ME_CONFIG_MONGODB_URL: mongodb://root:rootpassword@mongo:27017/
    depends_on:
      - mongo

volumes:
  mongo_data: